<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function custom_message_form_alter(array &$form, FormStateInterface $form_state, $form_id)
{
  if ($form_id === 'user_register_form') {
    $form['actions']['submit']['#submit'][] = 'custom_message_post_registration';
  }

  if ($form_id === 'user_register_form' || $form_id === 'user_form') {
    if (isset($form['field_phone'])) {
      $form['field_phone']['widget'][0]['value']['#attributes'] = [
        // "pattern" => "\+?[1-9][0-9]{0,2}[\s\-]?\(?[0-9]{1,4}\)?[\s\-]?[0-9]{1,4}[\s\-]?[0-9]{4,10}",
        "pattern" => "^\+?[0-9][0-9\-\(\)\s]{8,20}$",
        "title" => "Please enter a valid phone number.",
        "oninput" => "this.setCustomValidity('')"
      ];
    }
  }
}

/**
 * custom_message submit handler
 */
function custom_message_post_registration($form, FormStateInterface $form_state)
{
  \Drupal::messenger()->deleteByType('status');
  \Drupal::messenger()->addStatus(t('Welcome! Your registration has been successfully completed.'));
}






